version: '3.8'
services:
  server:
    build: ./server
    container_name: server
    ports:
      - '8081:8080'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client
    environment:
      - MONGO_URL=$MONGO_URL
      - PORT=$PORT
    ports:
      - '80:80'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
